# Generated by Django 5.0.7 on 2024-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('health', 'Health'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('author', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
