# Generated by Django 5.0.7 on 2024-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Techonlogy', 'Techonlogy'), ('Busniess', 'Busniess'), ('Entertainment', 'Entertainment'), ('Health', 'Health')], max_length=20),
        ),
    ]
